production:
  secret_key_base: <%= ENV["SECRET_KEY"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY"] %>


secret_key_base: <%= ENV["SECRET_KEY"] %>